<a href="https://colab.research.google.com/github/shubhankarsingh1003/Machine-Learning-Project-1/blob/main/ML_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Import Dataset

In [ ]:
dataset = pd.read_csv('mushroom_cleaned.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(dataset.isnull().sum())

cap-diameter       0
cap-shape          0
gill-attachment    0
gill-color         0
stem-height        0
stem-width         0
stem-color         0
season             0
class              0
dtype: int64


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [ ]:
print(X_train)

[[3.48000000e+02 0.00000000e+00 6.00000000e+00 ... 4.53000000e+02
  3.00000000e+00 8.88450288e-01]
 [8.65000000e+02 5.00000000e+00 5.00000000e+00 ... 1.80900000e+03
  1.00000000e+01 9.43194554e-01]
 [4.01000000e+02 6.00000000e+00 4.00000000e+00 ... 1.13600000e+03
  6.00000000e+00 9.43194554e-01]
 ...
 [8.80000000e+01 0.00000000e+00 0.00000000e+00 ... 8.30000000e+01
  6.00000000e+00 8.88450288e-01]
 [1.27600000e+03 2.00000000e+00 0.00000000e+00 ... 1.73500000e+03
  1.10000000e+01 9.43194554e-01]
 [7.65000000e+02 2.00000000e+00 5.00000000e+00 ... 1.22200000e+03
  7.00000000e+00 9.43194554e-01]]


In [ ]:
print(y_train)

[1 0 0 ... 1 0 0]


In [ ]:
print(X_test)

[[8.26000000e+02 2.00000000e+00 0.00000000e+00 ... 2.43300000e+03
  6.00000000e+00 1.80427271e+00]
 [5.71000000e+02 6.00000000e+00 2.00000000e+00 ... 7.61000000e+02
  4.00000000e+00 9.43194554e-01]
 [1.12200000e+03 2.00000000e+00 0.00000000e+00 ... 1.94200000e+03
  1.10000000e+01 9.43194554e-01]
 ...
 [7.57000000e+02 0.00000000e+00 2.00000000e+00 ... 1.23000000e+03
  1.10000000e+01 8.88450288e-01]
 [4.84000000e+02 1.00000000e+00 0.00000000e+00 ... 7.07000000e+02
  1.10000000e+01 8.88450288e-01]
 [7.25000000e+02 5.00000000e+00 1.00000000e+00 ... 9.55000000e+02
  6.00000000e+00 8.88450288e-01]]


In [ ]:
print(y_test)

[0 1 0 ... 1 1 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.60987154 -1.8504695   1.73320576 ... -0.76684122 -1.65899852
  -0.20683111]
 [ 0.82427063  0.46371662  1.28430535 ...  0.9647972   0.48465321
  -0.02701818]
 [-0.46285116  0.92655384  0.83540493 ...  0.10536309 -0.74029064
  -0.02701818]
 ...
 [-1.33110357 -1.8504695  -0.96019672 ... -1.23933843 -0.74029064
  -0.20683111]
 [ 1.96437205 -0.92479505 -0.96019672 ...  0.87029776  0.79088917
  -0.02701818]
 [ 0.5468737  -0.92479505  1.28430535 ...  0.21518676 -0.43405468
  -0.02701818]]


In [ ]:
print(X_test)

[[ 0.71608583 -0.92479505 -0.96019672 ...  1.76165735 -0.74029064
   2.80127774]
 [ 0.00872364  0.92655384 -0.06239589 ... -0.37351922 -1.35276256
  -0.02701818]
 [ 1.53718076 -0.92479505 -0.96019672 ...  1.13464079  0.79088917
  -0.02701818]
 ...
 [ 0.52468194 -1.8504695  -0.06239589 ...  0.22540292  0.79088917
  -0.20683111]
 [-0.2326117  -1.38763227 -0.96019672 ... -0.44247827  0.79088917
  -0.20683111]
 [ 0.43591492  0.46371662 -0.51129631 ... -0.12577744 -0.74029064
  -0.20683111]]


# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 42)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [ ]:
print(classifier.predict(sc.transform([[72,5,3,2,1.1583114894052096,492,12,0.8884502877862838]])))

[1]


In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [1 1]
 [1 1]
 [0 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[3271 2859]
 [2082 5297]]


0.6342438374417055

# K-Nearest Neighbors (K-NN)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
print(classifier.predict(sc.transform([[72,5,3,2,1.1583114894052096,492,12,0.8884502877862838]])))

[1]


In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 0]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[6040   90]
 [  56 7323]]


0.9891923902583463